version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint
    deploy-cfn:
      parameters:
        stack-name:
          description: Name of the CloudFormation stack
          type: string
      executor: aws-cli/default
      steps:
        - checkout
        - aws-cli/setup
        - run:
            name: Deploy Cloudformation Template with new Docker image
            command: |
              aws cloudformation deploy \
              --template Cloudformation/cloudformation.yml \
              --stack << parameters.stack-name >> \
              --parameter-overrides ImageTag=${CIRCLE_SHA1}
workflows:
  default:
    jobs:
      - init        
      - docker/publish:
          matrix:
            parameters:
              image: [$DOCKER_USERNAME/capstone-project]
              path: [app]
              docker-context: [app]
              deploy: [true]
              tag: ['$(<app/VERSION.txt)', 'latest']
              update-description: [true]    
          requires: [init]
    deploy:
      - deploy-cfn:
        context:
          - aws-12345-us-east-2
        stack-name: capstone-project
